# AI Study Buddy - Rule based ChatBOT

import datetime
import time

presentHour = datetime.datetime.now().hour

if presentHour < 12:
    print("Good Morning! ☀️")
elif presentHour < 18:
    print("Good Afternoon! 🌤️")
elif presentHour < 21:
    print("Good Evening! 🌆")
else:
    print("Good Night! 🌙")

print("Welcome to AI Study Buddy - Rule based ChatBOT!")
print("You can ask basic questions, Type 'bye' to exit the chat.")
time.sleep(1)

# Chatboy memory to store conversation history
responses = {
    "hi": "Hello! How can I assist you today?",
    "hello": "Hi there! What can I do for you?",
    "how are you?": "I'm just a bot, but I'm here to help you with your studies!",
    "what is python?": "Python is a popular programming language known for its simplicity and versatility.",
    "what is ai?": "Artificial Intelligence (AI) refers to the simulation of human intelligence in machines that are programmed to think and learn like humans.",
    "what is machine learning?": "Machine Learning is a subset of AI that focuses on enabling machines to learn from data and improve their performance over time without being explicitly programmed.",
    "what is deep learning?": "Deep Learning is a subset of Machine Learning that uses neural networks with many layers to analyze complex data and make predictions.",
    "what is data science?": "Data Science is an interdisciplinary field that uses scientific methods, processes, algorithms, and systems to extract knowledge and insights from structured and unstructured data.",
    "what is programming?": "Programming is the process of creating instructions that a computer can understand and execute to perform specific tasks or solve problems.",
    "what is coding?": "Coding is the act of writing instructions for computers using programming languages to create software, applications, and websites.",
    "what is algorithm?": "An algorithm is a step-by-step procedure or set of rules for solving a problem or performing a task, often used in computer programming and data processing.",
    "what is software?": "Software refers to the programs and other operating information used by a computer, including applications, operating systems, and utilities.",
    "what is hardware?": "Hardware refers to the physical components of a computer system,      such as the processor, memory, storage devices, and peripherals.",
    "what is cloud computing?": "Cloud computing is the delivery of computing services, including storage, processing power, and software, over the internet (the cloud) to offer faster innovation, flexible resources, and economies of scale.",
    "what is cybersecurity?": "Cybersecurity is the practice of protecting computer systems, networks, and data from digital attacks, unauthorized access, and damage.",
    "what is blockchain?": "Blockchain is a decentralized digital ledger that records transactions across many computers in such a way that the registered transactions cannot be altered retroactively, providing security and transparency.",
    "what is iot?": "The Internet of Things (IoT) refers to the network of physical objects embedded with sensors, software, and other technologies to connect and exchange data with other devices and systems over the internet.",
    "what is big data?": "Big Data refers to extremely large and complex data sets that require advanced tools and techniques to store, process, and analyze for insights and decision-making.",
    "what is ai study buddy?": "AI Study Buddy is a rule-based chatbot designed to assist students with their studies by providing answers to common questions about programming, AI, and related topics. It is a simple chatbot that uses predefined responses to engage in basic conversations and help users learn more about various subjects.",
    "who are you?": "I am AI Study Buddy, a rule-based chatbot created to assist you with your studies and answer your questions about programming, AI, and related topics.",
    "what can you do?": "I can answer basic questions about programming, AI, and related topics. I can also provide information and explanations to help you understand various concepts in these fields.",
    "bye": "Goodbye! Happy studying! | Made by: Rakshit Singh | with ❤️",
    "motivate me" : "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. - Rakshit Singh with ❤️",
    "happy" : "I'm glad to hear that! Keep up the good work!",
    "what is functions in python?" : "Functions in Python are reusable blocks of code that perform a specific task. They allow you to organize your code, make it more readable, and avoid repetition. You can define a function using the 'def' keyword, followed by the function name and parentheses. Inside the function, you can write the code that you want to execute when the function is called.",
    "tell me a joke" : "Why don't scientists trust atoms? Because they make up everything! - Rakshit Singh with ❤️",
    "tell me a fun fact" : "Did you know that the first computer programmer was a woman named Ada Lovelace? She wrote the first algorithm intended to be processed by a machine in the mid-1800s! - Rakshit Singh with ❤️",
    "tell me a story" : "Once upon a time, there was a curious student named Alex who wanted to learn programming. Alex found AI Study Buddy, a friendly chatbot that answered all of their questions about coding and AI. With the help of AI Study Buddy, Alex became a skilled programmer and went on to create amazing projects that made the world a better place! - Rakshit Singh with ❤️",
    "what is recursion?" : "Recursion is a programming technique where a function calls itself in order to solve a problem. It typically involves a base case that stops the recursion and a recursive case that breaks the problem into smaller subproblems. Recursion can simplify code and make it easier to read, but it can also lead to performance issues if not used carefully.",
    "what is object-oriented programming?" : "Object-oriented programming (OOP) is a programming paradigm that uses objects and classes to organize code. In OOP, you can create classes that define the properties and behaviors of objects, and then create instances of those classes to represent specific objects in your program. OOP promotes code reusability, modularity, and encapsulation, making it easier to manage and maintain complex software systems.",
    "what is oops in python?" : "OOPs in Python refers to Object-Oriented Programming in Python. It is a programming paradigm that uses classes and objects to structure code. In Python, you can define classes to create new data types, and then create instances of those classes to represent specific objects. OOPs in Python allows for code reusability, modularity, and encapsulation, making it easier to manage and maintain complex software systems.",
    "what is inheritance in python?" : "Inheritance in Python is a fundamental concept of object-oriented programming that allows a new class (called a child or subclass) to inherit attributes and methods from an existing class (called a parent or superclass). This promotes code reusability and helps to create a hierarchical relationship between classes. The child class can also override or extend the functionality of the parent class, allowing for more flexible and maintainable code.",
    "which is better flutter or react native?" : "Both Flutter and React Native are popular frameworks for building cross-platform mobile applications. Flutter, developed by Google, uses the Dart programming language and offers a rich set of pre-designed widgets, while React Native, developed by Facebook, uses JavaScript and allows for more flexibility in terms of design and development. The choice between the two depends on your specific project requirements, your familiarity with the programming languages, and your preferences for development tools and community support.",
    "what is the best programming language?" : "The best programming language depends on your specific needs and goals. Some popular programming languages include Python for its simplicity and versatility, JavaScript for web development, Java for enterprise applications, C++ for performance-critical applications, and many others. It's important to choose a programming language that aligns with your project requirements and your personal preferences as a developer.",
    "what is the future of AI?" : "The future of AI is promising and holds great potential for transforming various industries and aspects of our lives. AI is expected to continue advancing in areas such as natural language processing, computer vision, robotics, and machine learning. It has the potential to revolutionize healthcare, transportation, education, and many other fields by improving efficiency, enabling new capabilities, and enhancing decision-making. However, it also raises ethical considerations and challenges that need to be addressed to ensure responsible development and deployment of AI technologies.",
    "what is the capital of france?" : "The capital of France is Paris.",
    "what is the largest mammal?" : "The largest mammal is the blue whale.",
    "what is the smallest country?" : "The smallest country in the world is Vatican City.",
    "what is the tallest mountain?" : "The tallest mountain in the world is Mount Everest.",
    "what is the longest river?" : "The longest river in the world is the Nile River.",
    "what is the fastest land animal?" : "The fastest land animal is the cheetah.",
    "what is the largest desert?" : "The largest desert in the world is the Sahara Desert.",
    "what is the most spoken language?" : "The most spoken language in the world is Mandarin Chinese.",
    "which game is good for learning programming?" : "There are several games that can help you learn programming, such as 'CodeCombat', 'Robocode', 'Human Resource Machine', and 'TIS-100'. These games provide a fun and interactive way to practice coding concepts and improve your programming skills.",
    "what is file handling in python?" : "File handling in Python refers to the process of working with files, such as reading from and writing to files. Python provides built-in functions and methods for file handling, allowing you to create, open, read, write, and close files. You can use the 'open()' function to open a file, specify the mode (e.g., 'r' for reading, 'w' for writing), and then use methods like 'read()', 'write()', and 'close()' to perform various operations on the file. File handling is essential for tasks such as data storage, logging, and processing large datasets.",
    "what is exception handling in python?" : "Exception handling in Python is a mechanism to handle errors and exceptions that may occur during the execution of a program. It allows you to gracefully handle errors and prevent your program from crashing. In Python, you can use the 'try' and 'except' blocks to catch and handle exceptions. The code that may raise an exception is placed inside the 'try' block, and the code to handle the exception is placed inside the 'except' block. You can also use 'else' and 'finally' blocks for additional control over the flow of your program when handling exceptions.",
    "what is a list in python?" : "A list in Python is a built-in data structure that is used to store an ordered collection of items. Lists are mutable, meaning you can change their content after they have been created. You can create a list using square brackets [] and separate the items with commas. Lists can contain items of different data types, including other lists. They provide various methods for adding, removing, and manipulating the items in the list, making them a versatile and commonly used data structure in Python programming.",
    "what is a dictionary in python?" : "A dictionary in Python is a built-in data structure that is used to store key-value pairs. Dictionaries are mutable, meaning you can change their content after they have been created. You can create a dictionary using curly braces {} and separate the key-value pairs with commas. Each key in a dictionary must be unique, and it is used to access the corresponding value. Dictionaries provide various methods for adding, removing, and manipulating the key-value pairs, making them a powerful and flexible data structure in Python programming.",
    "what is a tuple in python?" : "A tuple in Python is a built-in data structure that is used to store an ordered collection of items. Tuples are immutable, meaning you cannot change their content after they have been created. You can create a tuple using parentheses () and separate the items with commas. Tuples can contain items of different data types, including other tuples. They provide various methods for accessing and manipulating the items in the tuple, making them a useful data structure for storing fixed collections of data in Python programming.",
    "what is a set in python?" : "A set in Python is a built-in data structure that is used to store an unordered collection of unique items. Sets are mutable, meaning you can change their content after they have been created. You can create a set using curly braces {} or the built-in 'set()' function. Sets do not allow duplicate items, and they provide various methods for adding, removing, and manipulating the items in the set. They are commonly used for operations such as membership testing, eliminating duplicates from a collection, and performing mathematical set operations like union, intersection, and difference in Python programming.",
    "what is chatbot?" : "A chatbot is a computer program designed to simulate conversation with human users, especially over the internet. Chatbots can be rule-based, like AI Study Buddy, which uses predefined responses to answer user questions, or they can be powered by artificial intelligence and machine learning algorithms to provide more dynamic and context-aware responses. Chatbots are commonly used in customer service, virtual assistants, and various applications to provide quick and efficient interactions with users.",
    "what is a rule-based chatbot?" : "A rule-based chatbot is a type of chatbot that operates based on a set of predefined rules and responses. It uses pattern matching to identify keywords or phrases in user input and responds with the corresponding predefined response. Rule-based chatbots are typically simpler and easier to implement than AI-powered chatbots, but they may not be able to handle complex or ambiguous user inputs as effectively. They are often used for basic customer service interactions, FAQs, and simple conversational applications.",
    "what is an ai-powered chatbot?" : "An AI-powered chatbot is a type of chatbot that uses artificial intelligence and machine learning algorithms to understand and respond to user input in a more dynamic and context-aware manner. Unlike rule-based chatbots, AI-powered chatbots can learn from interactions, adapt to new information, and provide more personalized responses. They can handle complex and ambiguous user inputs, making them suitable for a wider range of applications, including customer service, virtual assistants, and conversational agents in various domains.",
    "what is natural language processing?" : "Natural Language Processing (NLP) is a field of artificial intelligence that focuses on the interaction between computers and humans through natural language. It involves the development of algorithms and models that enable computers to understand, interpret, and generate human language in a way that is meaningful and useful. NLP is used in various applications, including chatbots, virtual assistants, sentiment analysis, language translation, and more, to facilitate communication between humans and machines.",
    "what is computer vision?" : "Computer Vision is a field of artificial intelligence that focuses on enabling computers to interpret and understand visual information from the world, such as images and videos. It involves the development of algorithms and models that allow computers to recognize objects, detect patterns, and make sense of visual data. Computer Vision is used in various applications, including image recognition, facial recognition, autonomous vehicles, medical imaging, and more, to enable machines to see and understand the visual world.",
    "what is robotics?" : "Robotics is a field of engineering and technology that focuses on the design, construction, operation, and use of robots. Robots are programmable machines that can perform tasks autonomously or with minimal human intervention. Robotics combines elements of mechanical engineering, electrical engineering, computer science, and artificial intelligence to create machines that can interact with the physical world and perform a wide range of tasks, from manufacturing and healthcare to exploration and entertainment.",
    "what is ai ethics?" : "AI ethics is a branch of ethics that focuses on the moral implications and considerations surrounding the development and use of artificial intelligence technologies. It addresses issues such as bias in AI algorithms, privacy concerns, accountability for AI decisions, and the impact of AI on society. AI ethics aims to ensure that AI technologies are developed and deployed in a responsible and ethical manner, taking into account the potential consequences for individuals and society as a whole.",
    "what is database" : "A database is an organized collection of data that is stored and accessed electronically. It allows for the efficient storage, retrieval, and management of data. Databases can be relational, where data is organized into tables with relationships between them, or non-relational, where data is stored in a more flexible format. Databases are used in various applications, including web development, business management, and data analysis, to store and manage large amounts of information.",
    "what is sql?" : "SQL (Structured Query Language) is a programming language used for managing and manipulating relational databases. It allows you to create, read, update, and delete data in a database using commands such as SELECT, INSERT, UPDATE, and DELETE. SQL is widely used in database management systems to perform various operations on data and is an essential skill for anyone working with databases.",
    "what is time" : f"The current time is: {time.strftime('%H:%M:%S')}",
    "what is date" : f"The current date is: {time.strftime('%Y-%m-%d')}",
    "what is datetime" : f"The current date and time is: {time.strftime('%Y-%m-%d %H:%M:%S')}",
    "what is your favourite car" : "As an AI Study Buddy, I don't have personal preferences, but I can tell you about some popular cars! Some of the most popular cars include the Tesla Model 3, Toyota Camry, Honda Accord, Ford Mustang, and BMW 3 Series. Each of these cars has its own unique features and appeal, so it really depends on what you're looking for in a car!",
    "what is your favourite programming language" : "As an AI Study Buddy, I don't have personal preferences, but I can tell you about some popular programming languages! Some of the most popular programming languages include Python, JavaScript, Java, C++, and Ruby. Each of these languages has its own strengths and use cases, so it really depends on what you're looking to do with programming!",
    "what is your favourite food" : "As an AI Study Buddy, I don't have personal preferences, but I can tell you about some popular foods! Some of the most popular foods around the world include pizza, sushi, burgers, pasta, and ice cream. Each of these foods has its own unique flavors and appeal, so it really depends on what you're in the mood for!",
    "what is your favourite movie" : "As an AI Study Buddy, I don't have personal preferences, but I can tell you about some popular movies! Some of the most popular movies include The Shawshank Redemption, The Godfather, The Dark Knight, Pulp Fiction, and Forrest Gump. Each of these movies has its own unique story and appeal, so it really depends on what genre or type of movie you're interested in!",
    "what is your favourite book" : "As an AI Study Buddy, I don't have personal preferences, but I can tell you about some popular books! Some of the most popular books include 'To Kill a Mockingbird' by Harper Lee, '1984' by George Orwell, 'The Great Gatsby' by F. Scott Fitzgerald, 'Harry Potter and the Sorcerer's Stone' by J.K. Rowling, and 'The Lord of the Rings' by J.R.R. Tolkien. Each of these books has its own unique story and appeal, so it really depends on what genre or type of book you're interested in!",
    "what is your favourite color" : "As an AI Study Buddy, I don't have personal preferences, but I can tell you about some popular colors! Some of the most popular colors include blue, red, green, yellow, and purple. Each of these colors has its own unique symbolism and appeal, so it really depends on what you're drawn to or what mood you're in!",
    "what is your favourite sport" : "As an AI Study Buddy, I don't have personal preferences, but I can tell you about some popular sports! Some of the most popular sports around the world include soccer (football), basketball, cricket, tennis, and baseball. Each of these sports has its own unique rules and appeal, so it really depends on what type of sport you're interested in or what you're looking to watch or play!",
    "what is your favourite music genre" : "As an AI Study Buddy, I don't have personal preferences, but I can tell you about some popular music genres! Some of the most popular music genres include pop, rock, hip-hop, country, and electronic dance music (EDM). Each of these genres has its own unique sound and appeal, so it really depends on what type of music you're in the mood for or what you enjoy listening to!",
    "sad" : "I'm sorry to hear that you're feeling sad. Remember that it's okay to feel this way sometimes, and it's important to take care of yourself. If you want to talk about what's making you feel sad, I'm here to listen and support you. You can also try doing something that makes you happy or reaching out to a friend or family member for support. Remember, you're not alone, and things will get better! - Rakshit Singh with ❤️",
    "why summer is so hot?" : "Summer is hot because of the tilt of the Earth's axis. During summer, the hemisphere tilted towards the sun receives more direct sunlight, which increases the temperature. Additionally, the longer daylight hours during summer allow for more time for the sun to heat the Earth's surface, contributing to the warmer temperatures.",
    "why is the sky blue?" : "The sky appears blue because of a phenomenon called Rayleigh scattering. When sunlight enters the Earth's atmosphere, it interacts with the molecules and small particles in the air. The shorter wavelengths of light (blue and violet) are scattered more than the longer wavelengths (red and orange). As a result, we see the sky as blue during the day. However, during sunrise and sunset, the light has to pass through more of the Earth's atmosphere, which scatters the shorter wavelengths even more and allows the longer wavelengths to dominate, giving the sky a reddish or orange hue.",
    "why do leaves change color in autumn?" : "Leaves change color in autumn due to a combination of factors, including changes in daylight and temperature. As the days get shorter and temperatures drop, the production of chlorophyll (the pigment responsible for the green color in leaves) slows down and eventually stops. As the chlorophyll breaks down, other pigments in the leaves become more visible. Carotenoids (which produce yellow and orange colors) and anthocyanins (which produce red and purple colors) are responsible for the vibrant colors we see in autumn foliage. The specific colors that appear can vary depending on the type of tree and environmental conditions.",
    "fastest means of transportation?" : "The fastest means of transportation currently is air travel, specifically commercial airplanes. The average cruising speed of a commercial jet is around 500 to 600 miles per hour (800 to 965 kilometers per hour). However, there are also supersonic aircraft, such as the Concorde, which could reach speeds of up to 1,354 miles per hour (2,180 kilometers per hour). In the future, there are plans for even faster modes of transportation, such as hypersonic vehicles and space travel, which could potentially reach speeds much higher than current commercial airplanes.",
    
}
# Method to get response from the bot based on user input

def getResponsefrombot(userquestion):
    userquestion = userquestion.lower()
    for eachkey in responses:
        if eachkey in userquestion:
            return responses[eachkey]
    return "I'm sorry, I don't have an answer for that question. Please try asking something else or check your spelling."

# Take user input

while True:
    userinput = input("Please enter your question: ").lower()
    reply = getResponsefrombot(userinput)
    print(f"AI Study Buddy: {reply}")

    if "bye" in userinput.lower():
        print("Goodbye! Happy studying! | Made by: Rakshit Singh | with ❤️")
        break